### ISSUE TITLE
Wie lange hält die powerbank? 

### ISSUE THREAD

**Issue by MubiTec** [pafra-123/AskSin_Uni_PCB#1]
Hi, was hast du für Langzeit Erfahrungen gemacht? Wie lange hält die powerbank?

**Comment by pafra-123** [comment]
Hi,
das hängt hauptsächlich von der Anzahl der LEDs und der verwendeten Powerbank ab.
Mit einer "XLYNE X41" Powerbank und der abgebildeten Lichterkette bin ich auf ziemlich genau 100 Stunden gekommen.
Siehe auch hier:
[https://homematic-forum.de/forum/viewtopic.php?f=76&t=53463&start=20#p538159](url)
