### ISSUE TITLE
Variante HB UNI Sen CAP MOIST

### ISSUE THREAD

**Issue by elmarfaber** [pafra-123/AskSin_Uni_PCB#2]
Hallo,

die o.g. Schaltung verweist auf das Projekt  jp112sdl/HB-UNI-Sen-CAP-MOIST. Der dortige Sketch passt leider nicht auf diese Schaltung, z.B. liest der Sketch die Batteriespannung an A0 aber laut Schaltplan wird dort der Sensor ausgelesen etc. Gibt es zu der Schaltung einen passenden Sketch?
Das Projekt AskSin++ ist super, doch sehr komplex. Ich habe leider keine Ahnung wie der Sketch, um die interne Spannungsmessung zu verwenden, umgeschrieben werden müßte.

Viele Grüße

Elmar

**Comment by pafra-123** [comment]
Hallo Elmar,

doch, die Platine passt eigentlich schon zum Sketch.
Es kann aber trotzdem immer wieder sein, dass sich der Sketch ändert.

Die Batteriespannung wird an A0 gemessen.
Das steht auch so im Schaltplan. Hierfür musst Du die Widerstände R1 und R2 bestücken.

Auf dem Schaltbild im Wiki hängt der Sensor-Pin auf "J3".
J3 = A3 auf dem Arduino.

Du musst den Sketch hier an Deine Bedürfnisse anpassen:
`const uint8_t SENSOR_PINS[]    {15, 16, 17}; //AOut Pins der Sensoren (hier A1, A2 und A3)`
Und zwar so:
`const uint8_t SENSOR_PINS[]    {17}; //AOut Pins der Sensoren (hier A3)`

Bitte beachte generell den Abschnitt "Code Flashen" auf der Seite von Jermome:
[https://github.com/jp112sdl/HB-UNI-Sen-CAP-MOIST#code-flashen](url)
Ich denke da auch speziell an den optionalen Temperatursensor.

**Comment by elmarfaber** [comment]
Ah jetzt wird es klarer, was mich verwirrt hat ist, dass im Schaltplan HB-UNI-Sen-CAP-MOIST steht mit R1 und R2 und A0. Ich dachte Spannungsteiler und Messung an A0. In der Basisvariante sind dann noch R4 und R5 bestückt, als es nicht funktionierte habe ich die beiden Widerstände eingelötet, dann ging die Messund an A3 natürlich gar nicht mehr...
Vielen Dank, jetzt funktioniert es!
